<?php 

$location = array(
  array('id' => '1101','parent' => '37','name' => 'Kab. Simeulue'),
  array('id' => '1102','parent' => '37','name' => 'Kab. Aceh Singkil'),
  array('id' => '1103','parent' => '37','name' => 'Kab. Aceh Selatan'),
  array('id' => '1104','parent' => '37','name' => 'Kab. Aceh Tenggara'),
  array('id' => '1105','parent' => '37','name' => 'Kab. Aceh Timur'),
  array('id' => '1106','parent' => '37','name' => 'Kab. Aceh Tengah'),
  array('id' => '1107','parent' => '37','name' => 'Kab. Aceh Barat'),
  array('id' => '1108','parent' => '37','name' => 'Kab. Aceh Besar'),
  array('id' => '1109','parent' => '37','name' => 'Kab. Pidie'),
  array('id' => '1110','parent' => '37','name' => 'Kab. Bireuen'),
  array('id' => '1111','parent' => '37','name' => 'Kab. Aceh Utara'),
  array('id' => '1112','parent' => '37','name' => 'Kab. Aceh Barat Daya'),
  array('id' => '1113','parent' => '37','name' => 'Kab. Gayo Lues'),
  array('id' => '1114','parent' => '37','name' => 'Kab. Aceh Tamiang'),
  array('id' => '1115','parent' => '37','name' => 'Kab. Nagan Raya'),
  array('id' => '1116','parent' => '37','name' => 'Kab. Aceh Jaya'),
  array('id' => '1117','parent' => '37','name' => 'Kab. Bener Meriah'),
  array('id' => '1118','parent' => '37','name' => 'Kab. Pidie Jaya'),
  array('id' => '1171','parent' => '37','name' => 'Kota Banda Aceh'),
  array('id' => '1172','parent' => '37','name' => 'Kota Sabang'),
  array('id' => '1173','parent' => '37','name' => 'Kota Langsa'),
  array('id' => '1174','parent' => '37','name' => 'Kota Lhokseumawe'),
  array('id' => '1175','parent' => '37','name' => 'Kota Subulussalam'),
  array('id' => '1201','parent' => '69','name' => 'Kab. Nias'),
  array('id' => '1202','parent' => '69','name' => 'Kab. Mandailing Natal'),
  array('id' => '1203','parent' => '69','name' => 'Kab. Tapanuli Selatan'),
  array('id' => '1204','parent' => '69','name' => 'Kab. Tapanuli Tengah'),
  array('id' => '1205','parent' => '69','name' => 'Kab. Tapanuli Utara'),
  array('id' => '1206','parent' => '69','name' => 'Kab. Toba Samosir'),
  array('id' => '1207','parent' => '69','name' => 'Kab. Labuhan Batu'),
  array('id' => '1208','parent' => '69','name' => 'Kab. Asahan'),
  array('id' => '1209','parent' => '69','name' => 'Kab. Simalungun'),
  array('id' => '1210','parent' => '69','name' => 'Kab. Dairi'),
  array('id' => '1211','parent' => '69','name' => 'Kab. Karo'),
  array('id' => '1212','parent' => '69','name' => 'Kab. Deli Serdang'),
  array('id' => '1213','parent' => '69','name' => 'Kab. Langkat'),
  array('id' => '1214','parent' => '69','name' => 'Kab. Nias Selatan'),
  array('id' => '1215','parent' => '69','name' => 'Kab. Humbang Hasundutan'),
  array('id' => '1216','parent' => '69','name' => 'Kab. Pakpak Bharat'),
  array('id' => '1217','parent' => '69','name' => 'Kab. Samosir'),
  array('id' => '1218','parent' => '69','name' => 'Kab. Serdang Bedagai'),
  array('id' => '1219','parent' => '69','name' => 'Kab. Batu Bara'),
  array('id' => '1220','parent' => '69','name' => 'Kab. Padang Lawas Utara'),
  array('id' => '1221','parent' => '69','name' => 'Kab. Padang Lawas'),
  array('id' => '1222','parent' => '69','name' => 'Kab. Labuhan Batu Selatan'),
  array('id' => '1223','parent' => '69','name' => 'Kab. Labuhan Batu Utara'),
  array('id' => '1224','parent' => '69','name' => 'Kab. Nias Utara'),
  array('id' => '1225','parent' => '69','name' => 'Kab. Nias Barat'),
  array('id' => '1271','parent' => '69','name' => 'Kota Sibolga'),
  array('id' => '1272','parent' => '69','name' => 'Kota Tanjung Balai'),
  array('id' => '1273','parent' => '69','name' => 'Kota Pematang Siantar'),
  array('id' => '1274','parent' => '69','name' => 'Kota Tebing Tinggi'),
  array('id' => '1275','parent' => '69','name' => 'Kota Medan'),
  array('id' => '1276','parent' => '69','name' => 'Kota Binjai'),
  array('id' => '1277','parent' => '69','name' => 'Kota Padangsidimpuan'),
  array('id' => '1278','parent' => '69','name' => 'Kota Gunungsitoli'),
  array('id' => '1301','parent' => '38','name' => 'Kab. Kep. Mentawai'),
  array('id' => '1302','parent' => '38','name' => 'Kab. Pesisir Selatan'),
  array('id' => '1303','parent' => '38','name' => 'Kab. Solok'),
  array('id' => '1304','parent' => '38','name' => 'Kab. Sijunjung'),
  array('id' => '1305','parent' => '38','name' => 'Kab. Tanah Datar'),
  array('id' => '1306','parent' => '38','name' => 'Kab. Padang Pariaman'),
  array('id' => '1307','parent' => '38','name' => 'Kab. Agam'),
  array('id' => '1308','parent' => '38','name' => 'Kab. Lima Puluh Kota'),
  array('id' => '1309','parent' => '38','name' => 'Kab. Pasaman'),
  array('id' => '1310','parent' => '38','name' => 'Kab. Solok Selatan'),
  array('id' => '1311','parent' => '38','name' => 'Kab. Dharmasraya'),
  array('id' => '1312','parent' => '38','name' => 'Kab. Pasaman Barat'),
  array('id' => '1371','parent' => '38','name' => 'Kota Padang'),
  array('id' => '1372','parent' => '38','name' => 'Kota Solok'),
  array('id' => '1373','parent' => '38','name' => 'Kota Sawah Lunto'),
  array('id' => '1374','parent' => '38','name' => 'Kota Padang Panjang'),
  array('id' => '1375','parent' => '38','name' => 'Kota Bukittinggi'),
  array('id' => '1376','parent' => '38','name' => 'Kota Payakumbuh'),
  array('id' => '1377','parent' => '38','name' => 'Kota Pariaman'),
  array('id' => '1401','parent' => '39','name' => 'Kab. Kuantan Singingi'),
  array('id' => '1402','parent' => '39','name' => 'Kab. Indragiri Hulu'),
  array('id' => '1403','parent' => '39','name' => 'Kab. Indragiri Hilir'),
  array('id' => '1404','parent' => '39','name' => 'Kab. Pelalawan'),
  array('id' => '1405','parent' => '39','name' => 'Kab. S I A K'),
  array('id' => '1406','parent' => '39','name' => 'Kab. Kampar'),
  array('id' => '1407','parent' => '39','name' => 'Kab. Rokan Hulu'),
  array('id' => '1408','parent' => '39','name' => 'Kab. Bengkalis'),
  array('id' => '1409','parent' => '39','name' => 'Kab. Rokan Hilir'),
  array('id' => '1410','parent' => '39','name' => 'Kab. Kep. Meranti'),
  array('id' => '1471','parent' => '39','name' => 'Kota Pekanbaru'),
  array('id' => '1473','parent' => '39','name' => 'Kota D U M A I'),
  array('id' => '1501','parent' => '40','name' => 'Kab. Kerinci'),
  array('id' => '1502','parent' => '40','name' => 'Kab. Merangin'),
  array('id' => '1503','parent' => '40','name' => 'Kab. Sarolangun'),
  array('id' => '1504','parent' => '40','name' => 'Kab. Batang Hari'),
  array('id' => '1505','parent' => '40','name' => 'Kab. Muaro Jambi'),
  array('id' => '1506','parent' => '40','name' => 'Kab. Tanjung Jabung Timur'),
  array('id' => '1507','parent' => '40','name' => 'Kab. Tanjung Jabung Barat'),
  array('id' => '1508','parent' => '40','name' => 'Kab. Tebo'),
  array('id' => '1509','parent' => '40','name' => 'Kab. Bungo'),
  array('id' => '1571','parent' => '40','name' => 'Kota Jambi'),
  array('id' => '1572','parent' => '40','name' => 'Kota Sungai Penuh'),
  array('id' => '1601','parent' => '41','name' => 'Kab. Ogan Komering Ulu'),
  array('id' => '1602','parent' => '41','name' => 'Kab. Ogan Komering Ilir'),
  array('id' => '1603','parent' => '41','name' => 'Kab. Muara Enim'),
  array('id' => '1604','parent' => '41','name' => 'Kab. Lahat'),
  array('id' => '1605','parent' => '41','name' => 'Kab. Musi Rawas'),
  array('id' => '1606','parent' => '41','name' => 'Kab. Musi Banyuasin'),
  array('id' => '1607','parent' => '41','name' => 'Kab. Banyu Asin'),
  array('id' => '1608','parent' => '41','name' => 'Kab. Ogan Komering Ulu Selatan'),
  array('id' => '1609','parent' => '41','name' => 'Kab. Ogan Komering Ulu Timur'),
  array('id' => '1610','parent' => '41','name' => 'Kab. Ogan Ilir'),
  array('id' => '1611','parent' => '41','name' => 'Kab. Empat Lawang'),
  array('id' => '1671','parent' => '41','name' => 'Kota Palembang'),
  array('id' => '1672','parent' => '41','name' => 'Kota Prabumulih'),
  array('id' => '1673','parent' => '41','name' => 'Kota Pagar Alam'),
  array('id' => '1674','parent' => '41','name' => 'Kota Lubuklinggau'),
  array('id' => '1701','parent' => '42','name' => 'Kab. Bengkulu Selatan'),
  array('id' => '1702','parent' => '42','name' => 'Kab. Rejang Lebong'),
  array('id' => '1703','parent' => '42','name' => 'Kab. Bengkulu Utara'),
  array('id' => '1704','parent' => '42','name' => 'Kab. Kaur'),
  array('id' => '1705','parent' => '42','name' => 'Kab. Seluma'),
  array('id' => '1706','parent' => '42','name' => 'Kab. Mukomuko'),
  array('id' => '1707','parent' => '42','name' => 'Kab. Lebong'),
  array('id' => '1708','parent' => '42','name' => 'Kab. Kepahiang'),
  array('id' => '1709','parent' => '42','name' => 'Kab. Bengkulu Tengah'),
  array('id' => '1771','parent' => '42','name' => 'Kota Bengkulu'),
  array('id' => '1801','parent' => '43','name' => 'Kab. Lampung Barat'),
  array('id' => '1802','parent' => '43','name' => 'Kab. Tanggamus'),
  array('id' => '1803','parent' => '43','name' => 'Kab. Lampung Selatan'),
  array('id' => '1804','parent' => '43','name' => 'Kab. Lampung Timur'),
  array('id' => '1805','parent' => '43','name' => 'Kab. Lampung Tengah'),
  array('id' => '1806','parent' => '43','name' => 'Kab. Lampung Utara'),
  array('id' => '1807','parent' => '43','name' => 'Kab. Way Kanan'),
  array('id' => '1808','parent' => '43','name' => 'Kab. Tulangbawang'),
  array('id' => '1809','parent' => '43','name' => 'Kab. Pesawaran'),
  array('id' => '1810','parent' => '43','name' => 'Kab. Pringsewu'),
  array('id' => '1811','parent' => '43','name' => 'Kab. Mesuji'),
  array('id' => '1812','parent' => '43','name' => 'Kab. Tulang Bawang Barat'),
  array('id' => '1871','parent' => '43','name' => 'Kota Bandar Lampung'),
  array('id' => '1872','parent' => '43','name' => 'Kota Metro'),
  array('id' => '1901','parent' => '44','name' => 'Kab. Bangka'),
  array('id' => '1902','parent' => '44','name' => 'Kab. Belitung'),
  array('id' => '1903','parent' => '44','name' => 'Kab. Bangka Barat'),
  array('id' => '1904','parent' => '44','name' => 'Kab. Bangka Tengah'),
  array('id' => '1905','parent' => '44','name' => 'Kab. Bangka Selatan'),
  array('id' => '1906','parent' => '44','name' => 'Kab. Belitung Timur'),
  array('id' => '1971','parent' => '44','name' => 'Kota Pangkal Pinang'),
  array('id' => '2101','parent' => '45','name' => 'Kab. Karimun'),
  array('id' => '2102','parent' => '45','name' => 'Kab. Bintan'),
  array('id' => '2103','parent' => '45','name' => 'Kab. Natuna'),
  array('id' => '2104','parent' => '45','name' => 'Kab. Lingga'),
  array('id' => '2105','parent' => '45','name' => 'Kab. Kep. Anambas'),
  array('id' => '2171','parent' => '45','name' => 'Kota B A T A M'),
  array('id' => '2172','parent' => '45','name' => 'Kota Tanjung Pinang'),
  array('id' => '3101','parent' => '46','name' => 'Kab. Kep. Seribu'),
  array('id' => '3171','parent' => '46','name' => 'Kota Jakarta Selatan'),
  array('id' => '3172','parent' => '46','name' => 'Kota Jakarta Timur'),
  array('id' => '3173','parent' => '46','name' => 'Kota Jakarta Pusat'),
  array('id' => '3174','parent' => '46','name' => 'Kota Jakarta Barat'),
  array('id' => '3175','parent' => '46','name' => 'Kota Jakarta Utara'),
  array('id' => '3201','parent' => '47','name' => 'Kab. Bogor'),
  array('id' => '3202','parent' => '47','name' => 'Kab. Sukabumi'),
  array('id' => '3203','parent' => '47','name' => 'Kab. Cianjur'),
  array('id' => '3204','parent' => '47','name' => 'Kab. Bandung'),
  array('id' => '3205','parent' => '47','name' => 'Kab. Garut'),
  array('id' => '3206','parent' => '47','name' => 'Kab. Tasikmalaya'),
  array('id' => '3207','parent' => '47','name' => 'Kab. Ciamis'),
  array('id' => '3208','parent' => '47','name' => 'Kab. Kuningan'),
  array('id' => '3209','parent' => '47','name' => 'Kab. Cirebon'),
  array('id' => '3210','parent' => '47','name' => 'Kab. Majalengka'),
  array('id' => '3211','parent' => '47','name' => 'Kab. Sumedang'),
  array('id' => '3212','parent' => '47','name' => 'Kab. Indramayu'),
  array('id' => '3213','parent' => '47','name' => 'Kab. Subang'),
  array('id' => '3214','parent' => '47','name' => 'Kab. Purwakarta'),
  array('id' => '3215','parent' => '47','name' => 'Kab. Karawang'),
  array('id' => '3216','parent' => '47','name' => 'Kab. Bekasi'),
  array('id' => '3217','parent' => '47','name' => 'Kab. Bandung Barat'),
  array('id' => '3271','parent' => '47','name' => 'Kota Bogor'),
  array('id' => '3272','parent' => '47','name' => 'Kota Sukabumi'),
  array('id' => '3273','parent' => '47','name' => 'Kota Bandung'),
  array('id' => '3274','parent' => '47','name' => 'Kota Cirebon'),
  array('id' => '3275','parent' => '47','name' => 'Kota Bekasi'),
  array('id' => '3276','parent' => '47','name' => 'Kota Depok'),
  array('id' => '3277','parent' => '47','name' => 'Kota Cimahi'),
  array('id' => '3278','parent' => '47','name' => 'Kota Tasikmalaya'),
  array('id' => '3279','parent' => '47','name' => 'Kota Banjar'),
  array('id' => '3301','parent' => '48','name' => 'Kab. Cilacap'),
  array('id' => '3302','parent' => '48','name' => 'Kab. Banyumas'),
  array('id' => '3303','parent' => '48','name' => 'Kab. Purbalingga'),
  array('id' => '3304','parent' => '48','name' => 'Kab. Banjarnegara'),
  array('id' => '3305','parent' => '48','name' => 'Kab. Kebumen'),
  array('id' => '3306','parent' => '48','name' => 'Kab. Purworejo'),
  array('id' => '3307','parent' => '48','name' => 'Kab. Wonosobo'),
  array('id' => '3308','parent' => '48','name' => 'Kab. Magelang'),
  array('id' => '3309','parent' => '48','name' => 'Kab. Boyolali'),
  array('id' => '3310','parent' => '48','name' => 'Kab. Klaten'),
  array('id' => '3311','parent' => '48','name' => 'Kab. Sukoharjo'),
  array('id' => '3312','parent' => '48','name' => 'Kab. Wonogiri'),
  array('id' => '3313','parent' => '48','name' => 'Kab. Karanganyar'),
  array('id' => '3314','parent' => '48','name' => 'Kab. Sragen'),
  array('id' => '3315','parent' => '48','name' => 'Kab. Grobogan'),
  array('id' => '3316','parent' => '48','name' => 'Kab. Blora'),
  array('id' => '3317','parent' => '48','name' => 'Kab. Rembang'),
  array('id' => '3318','parent' => '48','name' => 'Kab. Pati'),
  array('id' => '3319','parent' => '48','name' => 'Kab. Kudus'),
  array('id' => '3320','parent' => '48','name' => 'Kab. Jepara'),
  array('id' => '3321','parent' => '48','name' => 'Kab. Demak'),
  array('id' => '3322','parent' => '48','name' => 'Kab. Semarang'),
  array('id' => '3323','parent' => '48','name' => 'Kab. Temanggung'),
  array('id' => '3324','parent' => '48','name' => 'Kab. Kendal'),
  array('id' => '3325','parent' => '48','name' => 'Kab. Batang'),
  array('id' => '3326','parent' => '48','name' => 'Kab. Pekalongan'),
  array('id' => '3327','parent' => '48','name' => 'Kab. Pemalang'),
  array('id' => '3328','parent' => '48','name' => 'Kab. Tegal'),
  array('id' => '3329','parent' => '48','name' => 'Kab. Brebes'),
  array('id' => '3371','parent' => '48','name' => 'Kota Magelang'),
  array('id' => '3372','parent' => '48','name' => 'Kota Surakarta'),
  array('id' => '3373','parent' => '48','name' => 'Kota Salatiga'),
  array('id' => '3374','parent' => '48','name' => 'Kota Semarang'),
  array('id' => '3375','parent' => '48','name' => 'Kota Pekalongan'),
  array('id' => '3376','parent' => '48','name' => 'Kota Tegal'),
  array('id' => '3401','parent' => '49','name' => 'Kab. Kulon Progo'),
  array('id' => '3402','parent' => '49','name' => 'Kab. Bantul'),
  array('id' => '3403','parent' => '49','name' => 'Kab. Gunung Kidul'),
  array('id' => '3404','parent' => '49','name' => 'Kab. Sleman'),
  array('id' => '3471','parent' => '49','name' => 'Kota Yogyakarta'),
  array('id' => '3501','parent' => '50','name' => 'Kab. Pacitan'),
  array('id' => '3502','parent' => '50','name' => 'Kab. Ponorogo'),
  array('id' => '3503','parent' => '50','name' => 'Kab. Trenggalek'),
  array('id' => '3504','parent' => '50','name' => 'Kab. Tulungagung'),
  array('id' => '3505','parent' => '50','name' => 'Kab. Blitar'),
  array('id' => '3506','parent' => '50','name' => 'Kab. Kediri'),
  array('id' => '3507','parent' => '50','name' => 'Kab. Malang'),
  array('id' => '3508','parent' => '50','name' => 'Kab. Lumajang'),
  array('id' => '3509','parent' => '50','name' => 'Kab. Jember'),
  array('id' => '3510','parent' => '50','name' => 'Kab. Banyuwangi'),
  array('id' => '3511','parent' => '50','name' => 'Kab. Bondowoso'),
  array('id' => '3512','parent' => '50','name' => 'Kab. Situbondo'),
  array('id' => '3513','parent' => '50','name' => 'Kab. Probolinggo'),
  array('id' => '3514','parent' => '50','name' => 'Kab. Pasuruan'),
  array('id' => '3515','parent' => '50','name' => 'Kab. Sidoarjo'),
  array('id' => '3516','parent' => '50','name' => 'Kab. Mojokerto'),
  array('id' => '3517','parent' => '50','name' => 'Kab. Jombang'),
  array('id' => '3518','parent' => '50','name' => 'Kab. Nganjuk'),
  array('id' => '3519','parent' => '50','name' => 'Kab. Madiun'),
  array('id' => '3520','parent' => '50','name' => 'Kab. Magetan'),
  array('id' => '3521','parent' => '50','name' => 'Kab. Ngawi'),
  array('id' => '3522','parent' => '50','name' => 'Kab. Bojonegoro'),
  array('id' => '3523','parent' => '50','name' => 'Kab. Tuban'),
  array('id' => '3524','parent' => '50','name' => 'Kab. Lamongan'),
  array('id' => '3525','parent' => '50','name' => 'Kab. Gresik'),
  array('id' => '3526','parent' => '50','name' => 'Kab. Bangkalan'),
  array('id' => '3527','parent' => '50','name' => 'Kab. Sampang'),
  array('id' => '3528','parent' => '50','name' => 'Kab. Pamekasan'),
  array('id' => '3529','parent' => '50','name' => 'Kab. Sumenep'),
  array('id' => '3571','parent' => '50','name' => 'Kota Kediri'),
  array('id' => '3572','parent' => '50','name' => 'Kota Blitar'),
  array('id' => '3573','parent' => '50','name' => 'Kota Malang'),
  array('id' => '3574','parent' => '50','name' => 'Kota Probolinggo'),
  array('id' => '3575','parent' => '50','name' => 'Kota Pasuruan'),
  array('id' => '3576','parent' => '50','name' => 'Kota Mojokerto'),
  array('id' => '3577','parent' => '50','name' => 'Kota Madiun'),
  array('id' => '3578','parent' => '50','name' => 'Kota Surabaya'),
  array('id' => '3579','parent' => '50','name' => 'Kota Batu'),
  array('id' => '3601','parent' => '51','name' => 'Kab. Pandeglang'),
  array('id' => '3602','parent' => '51','name' => 'Kab. Lebak'),
  array('id' => '3603','parent' => '51','name' => 'Kab. Tangerang'),
  array('id' => '3604','parent' => '51','name' => 'Kab. Serang'),
  array('id' => '3671','parent' => '51','name' => 'Kota Tangerang'),
  array('id' => '3672','parent' => '51','name' => 'Kota Cilegon'),
  array('id' => '3673','parent' => '51','name' => 'Kota Serang'),
  array('id' => '3674','parent' => '51','name' => 'Kota Tangerang Selatan'),
  array('id' => '5101','parent' => '52','name' => 'Kab. Jembrana'),
  array('id' => '5102','parent' => '52','name' => 'Kab. Tabanan'),
  array('id' => '5103','parent' => '52','name' => 'Kab. Badung'),
  array('id' => '5104','parent' => '52','name' => 'Kab. Gianyar'),
  array('id' => '5105','parent' => '52','name' => 'Kab. Klungkung'),
  array('id' => '5106','parent' => '52','name' => 'Kab. Bangli'),
  array('id' => '5107','parent' => '52','name' => 'Kab. Karang Asem'),
  array('id' => '5108','parent' => '52','name' => 'Kab. Buleleng'),
  array('id' => '5171','parent' => '52','name' => 'Kota Denpasar'),
  array('id' => '5201','parent' => '53','name' => 'Kab. Lombok Barat'),
  array('id' => '5202','parent' => '53','name' => 'Kab. Lombok Tengah'),
  array('id' => '5203','parent' => '53','name' => 'Kab. Lombok Timur'),
  array('id' => '5204','parent' => '53','name' => 'Kab. Sumbawa'),
  array('id' => '5205','parent' => '53','name' => 'Kab. Dompu'),
  array('id' => '5206','parent' => '53','name' => 'Kab. Bima'),
  array('id' => '5207','parent' => '53','name' => 'Kab. Sumbawa Barat'),
  array('id' => '5208','parent' => '53','name' => 'Kab. Lombok Utara'),
  array('id' => '5271','parent' => '53','name' => 'Kota Mataram'),
  array('id' => '5272','parent' => '53','name' => 'Kota Bima'),
  array('id' => '5301','parent' => '54','name' => 'Kab. Sumba Barat'),
  array('id' => '5302','parent' => '54','name' => 'Kab. Sumba Timur'),
  array('id' => '5303','parent' => '54','name' => 'Kab. Kupang'),
  array('id' => '5304','parent' => '54','name' => 'Kab. Timor Tengah Selatan'),
  array('id' => '5305','parent' => '54','name' => 'Kab. Timor Tengah Utara'),
  array('id' => '5306','parent' => '54','name' => 'Kab. Belu'),
  array('id' => '5307','parent' => '54','name' => 'Kab. Alor'),
  array('id' => '5308','parent' => '54','name' => 'Kab. Lembata'),
  array('id' => '5309','parent' => '54','name' => 'Kab. Flores Timur'),
  array('id' => '5310','parent' => '54','name' => 'Kab. Sikka'),
  array('id' => '5311','parent' => '54','name' => 'Kab. Ende'),
  array('id' => '5312','parent' => '54','name' => 'Kab. Ngada'),
  array('id' => '5313','parent' => '54','name' => 'Kab. Manggarai'),
  array('id' => '5314','parent' => '54','name' => 'Kab. Rote Ndao'),
  array('id' => '5315','parent' => '54','name' => 'Kab. Manggarai Barat'),
  array('id' => '5316','parent' => '54','name' => 'Kab. Sumba Tengah'),
  array('id' => '5317','parent' => '54','name' => 'Kab. Sumba Barat Daya'),
  array('id' => '5318','parent' => '54','name' => 'Kab. Nagekeo'),
  array('id' => '5319','parent' => '54','name' => 'Kab. Manggarai Timur'),
  array('id' => '5320','parent' => '54','name' => 'Kab. Sabu Raijua'),
  array('id' => '5371','parent' => '54','name' => 'Kota Kupang'),
  array('id' => '6101','parent' => '55','name' => 'Kab. Sambas'),
  array('id' => '6102','parent' => '55','name' => 'Kab. Bengkayang'),
  array('id' => '6103','parent' => '55','name' => 'Kab. Landak'),
  array('id' => '6104','parent' => '55','name' => 'Kab. Pontianak'),
  array('id' => '6105','parent' => '55','name' => 'Kab. Sanggau'),
  array('id' => '6106','parent' => '55','name' => 'Kab. Ketapang'),
  array('id' => '6107','parent' => '55','name' => 'Kab. Sintang'),
  array('id' => '6108','parent' => '55','name' => 'Kab. Kapuas Hulu'),
  array('id' => '6109','parent' => '55','name' => 'Kab. Sekadau'),
  array('id' => '6110','parent' => '55','name' => 'Kab. Melawi'),
  array('id' => '6111','parent' => '55','name' => 'Kab. Kayong Utara'),
  array('id' => '6112','parent' => '55','name' => 'Kab. Kubu Raya'),
  array('id' => '6171','parent' => '55','name' => 'Kota Pontianak'),
  array('id' => '6172','parent' => '55','name' => 'Kota Singkawang'),
  array('id' => '6201','parent' => '56','name' => 'Kab. Kotawaringin Barat'),
  array('id' => '6202','parent' => '56','name' => 'Kab. Kotawaringin Timur'),
  array('id' => '6203','parent' => '56','name' => 'Kab. Kapuas'),
  array('id' => '6204','parent' => '56','name' => 'Kab. Barito Selatan'),
  array('id' => '6205','parent' => '56','name' => 'Kab. Barito Utara'),
  array('id' => '6206','parent' => '56','name' => 'Kab. Sukamara'),
  array('id' => '6207','parent' => '56','name' => 'Kab. Lamandau'),
  array('id' => '6208','parent' => '56','name' => 'Kab. Seruyan'),
  array('id' => '6209','parent' => '56','name' => 'Kab. Katingan'),
  array('id' => '6210','parent' => '56','name' => 'Kab. Pulang Pisau'),
  array('id' => '6211','parent' => '56','name' => 'Kab. Gunung Mas'),
  array('id' => '6212','parent' => '56','name' => 'Kab. Barito Timur'),
  array('id' => '6213','parent' => '56','name' => 'Kab. Murung Raya'),
  array('id' => '6271','parent' => '56','name' => 'Kota Palangka Raya'),
  array('id' => '6301','parent' => '57','name' => 'Kab. Tanah Laut'),
  array('id' => '6302','parent' => '57','name' => 'Kab. Kota Baru'),
  array('id' => '6303','parent' => '57','name' => 'Kab. Banjar'),
  array('id' => '6304','parent' => '57','name' => 'Kab. Barito Kuala'),
  array('id' => '6305','parent' => '57','name' => 'Kab. Tapin'),
  array('id' => '6306','parent' => '57','name' => 'Kab. Hulu Sungai Selatan'),
  array('id' => '6307','parent' => '57','name' => 'Kab. Hulu Sungai Tengah'),
  array('id' => '6308','parent' => '57','name' => 'Kab. Hulu Sungai Utara'),
  array('id' => '6309','parent' => '57','name' => 'Kab. Tabalong'),
  array('id' => '6310','parent' => '57','name' => 'Kab. Tanah Bumbu'),
  array('id' => '6311','parent' => '57','name' => 'Kab. Balangan'),
  array('id' => '6371','parent' => '57','name' => 'Kota Banjarmasin'),
  array('id' => '6372','parent' => '57','name' => 'Kota Banjar Baru'),
  array('id' => '6401','parent' => '58','name' => 'Kab. Paser'),
  array('id' => '6402','parent' => '58','name' => 'Kab. Kutai Barat'),
  array('id' => '6403','parent' => '58','name' => 'Kab. Kutai Kartanegara'),
  array('id' => '6404','parent' => '58','name' => 'Kab. Kutai Timur'),
  array('id' => '6405','parent' => '58','name' => 'Kab. Berau'),
  array('id' => '6406','parent' => '58','name' => 'Kab. Malinau'),
  array('id' => '6407','parent' => '58','name' => 'Kab. Bulungan'),
  array('id' => '6408','parent' => '58','name' => 'Kab. Nunukan'),
  array('id' => '6409','parent' => '58','name' => 'Kab. Penajam Paser Utara'),
  array('id' => '6410','parent' => '58','name' => 'Kab. Tana Tidung'),
  array('id' => '6471','parent' => '58','name' => 'Kota Balikpapan'),
  array('id' => '6472','parent' => '58','name' => 'Kota Samarinda'),
  array('id' => '6473','parent' => '58','name' => 'Kota Tarakan'),
  array('id' => '6474','parent' => '58','name' => 'Kota Bontang'),
  array('id' => '7101','parent' => '59','name' => 'Kab. Bolaang Mongondow'),
  array('id' => '7102','parent' => '59','name' => 'Kab. Minahasa'),
  array('id' => '7103','parent' => '59','name' => 'Kab. Kep. Sangihe'),
  array('id' => '7104','parent' => '59','name' => 'Kab. Kep. Talaud'),
  array('id' => '7105','parent' => '59','name' => 'Kab. Minahasa Selatan'),
  array('id' => '7106','parent' => '59','name' => 'Kab. Minahasa Utara'),
  array('id' => '7107','parent' => '59','name' => 'Kab. Bolaang Mongondow Utara'),
  array('id' => '7108','parent' => '59','name' => 'Kab. Siau Tagulandang Biaro'),
  array('id' => '7109','parent' => '59','name' => 'Kab. Minahasa Tenggara'),
  array('id' => '7110','parent' => '59','name' => 'Kab. Bolaang Mongondow Selatan'),
  array('id' => '7111','parent' => '59','name' => 'Kab. Bolaang Mongondow Timur'),
  array('id' => '7171','parent' => '59','name' => 'Kota Manado'),
  array('id' => '7172','parent' => '59','name' => 'Kota Bitung'),
  array('id' => '7173','parent' => '59','name' => 'Kota Tomohon'),
  array('id' => '7174','parent' => '59','name' => 'Kota Kotamobagu'),
  array('id' => '7201','parent' => '60','name' => 'Kab. Banggai Kep.'),
  array('id' => '7202','parent' => '60','name' => 'Kab. Banggai'),
  array('id' => '7203','parent' => '60','name' => 'Kab. Morowali'),
  array('id' => '7204','parent' => '60','name' => 'Kab. Poso'),
  array('id' => '7205','parent' => '60','name' => 'Kab. Donggala'),
  array('id' => '7206','parent' => '60','name' => 'Kab. Toli-Toli'),
  array('id' => '7207','parent' => '60','name' => 'Kab. Buol'),
  array('id' => '7208','parent' => '60','name' => 'Kab. Parigi Moutong'),
  array('id' => '7209','parent' => '60','name' => 'Kab. Tojo Una-Una'),
  array('id' => '7210','parent' => '60','name' => 'Kab. Sigi'),
  array('id' => '7271','parent' => '60','name' => 'Kota Palu'),
  array('id' => '7301','parent' => '61','name' => 'Kab. Kep. Selayar'),
  array('id' => '7302','parent' => '61','name' => 'Kab. Bulukumba'),
  array('id' => '7303','parent' => '61','name' => 'Kab. Bantaeng'),
  array('id' => '7304','parent' => '61','name' => 'Kab. Jeneponto'),
  array('id' => '7305','parent' => '61','name' => 'Kab. Takalar'),
  array('id' => '7306','parent' => '61','name' => 'Kab. Gowa'),
  array('id' => '7307','parent' => '61','name' => 'Kab. Sinjai'),
  array('id' => '7308','parent' => '61','name' => 'Kab. Maros'),
  array('id' => '7309','parent' => '61','name' => 'Kab. Pangkajene Dan Kep.'),
  array('id' => '7310','parent' => '61','name' => 'Kab. Barru'),
  array('id' => '7311','parent' => '61','name' => 'Kab. Bone'),
  array('id' => '7312','parent' => '61','name' => 'Kab. Soppeng'),
  array('id' => '7313','parent' => '61','name' => 'Kab. Wajo'),
  array('id' => '7314','parent' => '61','name' => 'Kab. Sidenreng Rappang'),
  array('id' => '7315','parent' => '61','name' => 'Kab. Pinrang'),
  array('id' => '7316','parent' => '61','name' => 'Kab. Enrekang'),
  array('id' => '7317','parent' => '61','name' => 'Kab. Luwu'),
  array('id' => '7318','parent' => '61','name' => 'Kab. Tana Toraja'),
  array('id' => '7322','parent' => '61','name' => 'Kab. Luwu Utara'),
  array('id' => '7325','parent' => '61','name' => 'Kab. Luwu Timur'),
  array('id' => '7326','parent' => '61','name' => 'Kab. Toraja Utara'),
  array('id' => '7371','parent' => '61','name' => 'Kota Makassar'),
  array('id' => '7372','parent' => '61','name' => 'Kota Pare-Pare'),
  array('id' => '7373','parent' => '61','name' => 'Kota Palopo'),
  array('id' => '7401','parent' => '62','name' => 'Kab. Buton'),
  array('id' => '7402','parent' => '62','name' => 'Kab. Muna'),
  array('id' => '7403','parent' => '62','name' => 'Kab. Konawe'),
  array('id' => '7404','parent' => '62','name' => 'Kab. Kolaka'),
  array('id' => '7405','parent' => '62','name' => 'Kab. Konawe Selatan'),
  array('id' => '7406','parent' => '62','name' => 'Kab. Bombana'),
  array('id' => '7407','parent' => '62','name' => 'Kab. Wakatobi'),
  array('id' => '7408','parent' => '62','name' => 'Kab. Kolaka Utara'),
  array('id' => '7409','parent' => '62','name' => 'Kab. Buton Utara'),
  array('id' => '7410','parent' => '62','name' => 'Kab. Konawe Utara'),
  array('id' => '7471','parent' => '62','name' => 'Kota Kendari'),
  array('id' => '7472','parent' => '62','name' => 'Kota Baubau'),
  array('id' => '7501','parent' => '63','name' => 'Kab. Boalemo'),
  array('id' => '7502','parent' => '63','name' => 'Kab. Gorontalo'),
  array('id' => '7503','parent' => '63','name' => 'Kab. Pohuwato'),
  array('id' => '7504','parent' => '63','name' => 'Kab. Bone Bolango'),
  array('id' => '7505','parent' => '63','name' => 'Kab. Gorontalo Utara'),
  array('id' => '7571','parent' => '63','name' => 'Kota Gorontalo'),
  array('id' => '7601','parent' => '64','name' => 'Kab. Majene'),
  array('id' => '7602','parent' => '64','name' => 'Kab. Polewali Mandar'),
  array('id' => '7603','parent' => '64','name' => 'Kab. Mamasa'),
  array('id' => '7604','parent' => '64','name' => 'Kab. Mamuju'),
  array('id' => '7605','parent' => '64','name' => 'Kab. Mamuju Utara'),
  array('id' => '8101','parent' => '65','name' => 'Kab. Maluku Tenggara Barat'),
  array('id' => '8102','parent' => '65','name' => 'Kab. Maluku Tenggara'),
  array('id' => '8103','parent' => '65','name' => 'Kab. Maluku Tengah'),
  array('id' => '8104','parent' => '65','name' => 'Kab. Buru'),
  array('id' => '8105','parent' => '65','name' => 'Kab. Kep. Aru'),
  array('id' => '8106','parent' => '65','name' => 'Kab. Seram Bagian Barat'),
  array('id' => '8107','parent' => '65','name' => 'Kab. Seram Bagian Timur'),
  array('id' => '8108','parent' => '65','name' => 'Kab. Maluku Barat Daya'),
  array('id' => '8109','parent' => '65','name' => 'Kab. Buru Selatan'),
  array('id' => '8171','parent' => '65','name' => 'Kota Ambon'),
  array('id' => '8172','parent' => '65','name' => 'Kota Tual'),
  array('id' => '8201','parent' => '66','name' => 'Kab. Halmahera Barat'),
  array('id' => '8202','parent' => '66','name' => 'Kab. Halmahera Tengah'),
  array('id' => '8203','parent' => '66','name' => 'Kab. Kep. Sula'),
  array('id' => '8204','parent' => '66','name' => 'Kab. Halmahera Selatan'),
  array('id' => '8205','parent' => '66','name' => 'Kab. Halmahera Utara'),
  array('id' => '8206','parent' => '66','name' => 'Kab. Halmahera Timur'),
  array('id' => '8207','parent' => '66','name' => 'Kab. Pulau Morotai'),
  array('id' => '8271','parent' => '66','name' => 'Kota Ternate'),
  array('id' => '8272','parent' => '66','name' => 'Kota Tidore Kep.'),
  array('id' => '9101','parent' => '67','name' => 'Kab. Fakfak'),
  array('id' => '9102','parent' => '67','name' => 'Kab. Kaimana'),
  array('id' => '9103','parent' => '67','name' => 'Kab. Teluk Wondama'),
  array('id' => '9104','parent' => '67','name' => 'Kab. Teluk Bintuni'),
  array('id' => '9105','parent' => '67','name' => 'Kab. Manokwari'),
  array('id' => '9106','parent' => '67','name' => 'Kab. Sorong Selatan'),
  array('id' => '9107','parent' => '67','name' => 'Kab. Sorong'),
  array('id' => '9108','parent' => '67','name' => 'Kab. Raja Ampat'),
  array('id' => '9109','parent' => '67','name' => 'Kab. Tambrauw'),
  array('id' => '9110','parent' => '67','name' => 'Kab. Maybrat'),
  array('id' => '9171','parent' => '67','name' => 'Kota Sorong'),
  array('id' => '9401','parent' => '68','name' => 'Kab. Merauke'),
  array('id' => '9402','parent' => '68','name' => 'Kab. Jayawijaya'),
  array('id' => '9403','parent' => '68','name' => 'Kab. Jayapura'),
  array('id' => '9404','parent' => '68','name' => 'Kab. Nabire'),
  array('id' => '9408','parent' => '68','name' => 'Kab. Kep. Yapen'),
  array('id' => '9409','parent' => '68','name' => 'Kab. Biak Numfor'),
  array('id' => '9410','parent' => '68','name' => 'Kab. Paniai'),
  array('id' => '9411','parent' => '68','name' => 'Kab. Puncak Jaya'),
  array('id' => '9412','parent' => '68','name' => 'Kab. Mimika'),
  array('id' => '9413','parent' => '68','name' => 'Kab. Boven Digoel'),
  array('id' => '9414','parent' => '68','name' => 'Kab. Mappi'),
  array('id' => '9415','parent' => '68','name' => 'Kab. Asmat'),
  array('id' => '9416','parent' => '68','name' => 'Kab. Yahukimo'),
  array('id' => '9417','parent' => '68','name' => 'Kab. Pegunungan Bintang'),
  array('id' => '9418','parent' => '68','name' => 'Kab. Tolikara'),
  array('id' => '9419','parent' => '68','name' => 'Kab. Sarmi'),
  array('id' => '9420','parent' => '68','name' => 'Kab. Keerom'),
  array('id' => '9426','parent' => '68','name' => 'Kab. Waropen'),
  array('id' => '9427','parent' => '68','name' => 'Kab. Supiori'),
  array('id' => '9428','parent' => '68','name' => 'Kab. Mamberamo Raya'),
  array('id' => '9429','parent' => '68','name' => 'Kab. Nduga'),
  array('id' => '9430','parent' => '68','name' => 'Kab. Lanny Jaya'),
  array('id' => '9431','parent' => '68','name' => 'Kab. Mamberamo Tengah'),
  array('id' => '9432','parent' => '68','name' => 'Kab. Yalimo'),
  array('id' => '9433','parent' => '68','name' => 'Kab. Puncak'),
  array('id' => '9434','parent' => '68','name' => 'Kab. Dogiyai'),
  array('id' => '9435','parent' => '68','name' => 'Kab. Intan Jaya'),
  array('id' => '9436','parent' => '68','name' => 'Kab. Deiyai'),
  array('id' => '9471','parent' => '68','name' => 'Kota Jayapura')
);

function slugify($text)
{ 
  // replace non letter or digits by -
  $text = preg_replace('~[^\\pL\d]+~u', '-', $text);

  // trim
  $text = trim($text, '-');

  // transliterate
  $text = iconv('utf-8', 'us-ascii//TRANSLIT', $text);

  // lowercase
  $text = strtolower($text);

  // remove unwanted characters
  $text = preg_replace('~[^-\w]+~', '', $text);

  if (empty($text))
  {
    return 'n-a';
  }

  return $text;
}


foreach ($location as $lokasi ) {
	echo slugify($lokasi['name']) . '<br/>';
}
 
foreach ($location as $lokasi ) {
	wp_insert_term(
	  $lokasi['name'], // the term 
	  'direktori_wilayah', // the taxonomy
	  array(
	    'description'=> '',
	    'slug' => slugify($lokasi['name']),
	    'parent'=> $lokasi['parent']
	  )
	);
}


 ?>